// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL4NAJl0t7AG5h_2NgYVKNJOuh03kuWTg',
    appId: '1:919593783110:web:a4fedd297ff99fc9e61f47',
    messagingSenderId: '919593783110',
    projectId: 'jumpbook-2e3f5',
    authDomain: 'jumpbook-2e3f5.firebaseapp.com',
    storageBucket: 'jumpbook-2e3f5.firebasestorage.app',
    measurementId: 'G-35QM466KSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_uz_a2Mq6-KCnG3NQEmTErkeB-KyqmM',
    appId: '1:919593783110:android:9dd40bd5fb1e4540e61f47',
    messagingSenderId: '919593783110',
    projectId: 'jumpbook-2e3f5',
    storageBucket: 'jumpbook-2e3f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKPTAD31MsIEWoC7Cpj3itWxfnupWN54',
    appId: '1:919593783110:ios:9d2f2c4ba68a6afde61f47',
    messagingSenderId: '919593783110',
    projectId: 'jumpbook-2e3f5',
    storageBucket: 'jumpbook-2e3f5.firebasestorage.app',
    iosBundleId: 'com.example.jumpbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByKPTAD31MsIEWoC7Cpj3itWxfnupWN54',
    appId: '1:919593783110:ios:9d2f2c4ba68a6afde61f47',
    messagingSenderId: '919593783110',
    projectId: 'jumpbook-2e3f5',
    storageBucket: 'jumpbook-2e3f5.firebasestorage.app',
    iosBundleId: 'com.example.jumpbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL4NAJl0t7AG5h_2NgYVKNJOuh03kuWTg',
    appId: '1:919593783110:web:ce467d306f926bd9e61f47',
    messagingSenderId: '919593783110',
    projectId: 'jumpbook-2e3f5',
    authDomain: 'jumpbook-2e3f5.firebaseapp.com',
    storageBucket: 'jumpbook-2e3f5.firebasestorage.app',
    measurementId: 'G-LE9BX9HJVL',
  );
}
